# Generated by Django 2.1.5 on 2019-02-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotastat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='denies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gpm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='healing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='items',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='networth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xpm',
            field=models.IntegerField(default=0),
        ),
    ]
