# Generated by Django 2.1.5 on 2019-02-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotastat', '0002_auto_20190209_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bld',
        ),
        migrations.RemoveField(
            model_name='player',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='player',
            name='denies',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gpm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='healing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='player',
            name='items',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_hits',
        ),
        migrations.RemoveField(
            model_name='player',
            name='networth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num',
        ),
        migrations.RemoveField(
            model_name='player',
            name='xpm',
        ),
    ]
