# Generated by Django 2.1.5 on 2019-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotastat', '0005_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='gamemode',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='lobby',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.CharField(default='', max_length=150),
        ),
    ]
